### ISSUE TITLE
cannot build for target x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by EverlastingBugstopper** [denoland/rusty_v8#651] opened 2021-03-24 15:53 UTC
Hey y'all! I'm not sure if this is intended or documented somewhere but it seems as if `rusty_v8` does not play well with `musl-tools`. (It looks like y'all are currently [only building for](https://github.com/denoland/rusty_v8/blob/25608cc00069b5e267413e643aea8c9ff76e0e78/.github/workflows/ci.yml#L22) `x86_64-unknown-linux-gnu` so this issue may just be out of scope).

I've made a minimally reproducible example with [this repo](https://github.com/EverlastingBugstopper/deno-repro-repo) that includes `rusty_v8` as a dependency, and prints `Hello, World`.

I have a [GitHub Action](https://github.com/EverlastingBugstopper/deno-repro-repo/blob/main/.github/workflows/build.yml) set up to build this crate with the following steps:

```yaml
name: Build Release

on: push
    
jobs:
  build:
    name: Repro compilation bug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install musl-tools
        run: |
          sudo apt-get update -y
          sudo apt-get install musl-tools -y

      - name: Install rust
        run: |
          rustup target add x86_64-unknown-linux-musl 

      - name: Build
        run: cargo build --verbose --target x86_64-unknown-linux-musl
```

The `Build` step fails with the following error

```console
$ cargo build --verbose --target x86_64-unknown-linux-musl
...
Running `rustc --crate-name rusty_v8 --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.21.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=31fe65957a7061ea -C extra-filename=-31fe65957a7061ea --out-dir /home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps --target x86_64-unknown-linux-musl -L dependency=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps -L dependency=/home/runner/work/deno-repro-repo/deno-repro-repo/target/debug/deps --extern bitflags=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/libbitflags-b8acbdbf0b53393e.rmeta --extern lazy_static=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/liblazy_static-7c4d90068fb1f81e.rmeta --extern libc=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/liblibc-e1042c81b5256201.rmeta --cap-lints allow -L /home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/gn_out/obj -l static=rusty_v8`
error: failed to add native library /home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/gn_out/obj/librusty_v8.a: file too small to be an archive

error: aborting due to previous error

error: could not compile `rusty_v8`

Caused by:
  process didn't exit successfully: `rustc --crate-name rusty_v8 --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.21.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=31fe65957a7061ea -C extra-filename=-31fe65957a7061ea --out-dir /home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps --target x86_64-unknown-linux-musl -L dependency=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps -L dependency=/home/runner/work/deno-repro-repo/deno-repro-repo/target/debug/deps --extern bitflags=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/libbitflags-b8acbdbf0b53393e.rmeta --extern lazy_static=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/liblazy_static-7c4d90068fb1f81e.rmeta --extern libc=/home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/deps/liblibc-e1042c81b5256201.rmeta --cap-lints allow -L /home/runner/work/deno-repro-repo/deno-repro-repo/target/x86_64-unknown-linux-musl/debug/gn_out/obj -l static=rusty_v8` (exit code: 1)
```

The full verbose failure logs [here](https://github.com/EverlastingBugstopper/deno-repro-repo/runs/2185712655?check_suite_focus=true).

Please let me know if there's any way I can help!

**Comment by ry** [comment] 2021-03-24 16:12
duplicate of #49

**Closed by ry** 2021-03-24 16:12 UTC
