### ISSUE TITLE
Callbacks passed to `Function::new` should be `UnwindSafe`. 

### ISSUE THREAD

**Issue by m-hilgendorf** [denoland/rusty_v8#1391] opened 2024-01-29 20:47 UTC
This applies to other APIs that take callbacks such like mentioned in #534.  This can help avoid [undefined behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) when a Rust function is called from C++ and panics. 

If the trait bound is too high a burden as it's a breaking change, the API implementations should use `catch_unwind` or mark functions that take callbacks as arguments as `unsafe` (which they currently are). Otherwise it should be well documented that panicking will (hopefully) crash the process when unwinding fails, whereas a normal panic would only crash a thread.

**Comment by devsnek** [comment] 2024-07-02 03:00
I'm going to close this as a duplicate of https://github.com/denoland/rusty_v8/issues/534, and we can track it there.

**Closed by devsnek** 2024-07-02 03:00 UTC

**Comment by m-hilgendorf** [comment] 2024-07-02 03:25
Thank you for taking a look at this!
